version: '3.8'

x-common-env: &common-env
  TZ: ${TZ:-Europe/Moscow}
  AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
  AIRFLOW__CORE__LOAD_DEFAULT_CONNECTIONS: 'false'
  AIRFLOW__CORE__EXECUTOR: LocalExecutor
  AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${DB_USER}:${DB_PASSWORD}@db:${DB_PORT}/${DB_NAME}

services:
  airflow:
    container_name: airflow
    build:
      context: .
      dockerfile: Dockerfile
      args:
        AIRFLOW_VERSION: ${AIRFLOW_VERSION}
    env_file:
      - .env
    platform: linux/amd64
    ports:
      - "${AIRFLOW_PORT:-8080}:8080"
      - "${DBT_PORT:-9090}:9090"
    volumes:
      - ${BASE_PATH:-./}/dags:/opt/airflow/dags
      - ./volumes/logs:/opt/airflow/logs
      - ./volumes/plugins:/opt/airflow/plugins
      - ./volumes/config:/opt/airflow/config
      - ./workflow_tools:/opt/airflow/workflow_tools
      - ./dbt_projects:/opt/airflow/dbt_projects
    environment:
      <<: *common-env
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: postgres
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: ${DB_USER:-airflow}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-airflow}
      POSTGRES_DB: ${DB_NAME:-airflow}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT:-5432}:5432"
    restart: unless-stopped

