jaffle_shop:
  target: target
  outputs:
    dev:
      type: postgres
      threads: 1
      host: db
      port: 5432
      user: postgres
      pass: postgres
      dbname: postgres
      schema: dbt_example

